### ISSUE TITLE
Search says no results when there are

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/docs.ubuntu.com#149]
When you search the docs. The results page says no results found but there are a few listed:
![screenshot-2018-4-17 ubuntu documentation](https://user-images.githubusercontent.com/1413534/38873764-6fc45998-424e-11e8-9fff-98f013b21b71.png)

**Comment by WillMoggridge** [comment]
I did some work previously on this repo, which may be related to this.
https://github.com/canonical-webteam/gsa/pull/5

I was unable to release my code due to lack of permissions on Pypi for this package, it currently belongs to @nottrobin. It is probably worth testing/deploying the latest code and checking the output.

**Comment by nottrobin** [comment]
@WillMoggridge published at https://pypi.org/project/canonicalwebteam.gsa/
