### ISSUE TITLE
Search Google for landscape on premises, returns 500 link

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-websites/docs.ubuntu.com#208]
## Summary

Search Google for landscape on premises
Get https://docs.ubuntu.com/landscape/en/onprem-overview as one of results
get 500

## Current and expected result

Expect old pages to not be  in Google..

**Comment by nottrobin** [comment]
The real problem here is that the first result in [our search results for "landscape on premises" ](https://www.ubuntu.com/search?q=landscape+on+premises&domain=docs.ubuntu.com%2Flandscape) takes you to an error page. The fact that it's a 500 when it should be a 404 is secondary to this primary point.

So the first and most important fix is to redirect https://docs.ubuntu.com/landscape/en/onprem-overview to https://docs.ubuntu.com/landscape/en/onprem.

Then, we should definitely fix the 500 so it correctly displays a 404, but given its an error page either way, I think it's okay for us to take the time to properly fix 404s for Django v2. Rolling back seems definitely too drastic.

I'm going to close this PR now, and file my own PR to add the redirect, and see if I can fix the 500/404 issue at the same time.
