### ISSUE TITLE
No clear pattern for associating related sets of documentation

### ISSUE THREAD

**Issue by caldav** [canonical-websites/docs.ubuntu.com#41]
The addition of [the stacks doc to docs.ubuntu.com/core](https://github.com/CanonicalLtd/ubuntu-core-docs/pull/8) sets a precedent for merging several doc sources in a single doc build and is not inline with current usage of the platform. We should have platform-wide pattern and tools for these use cases.

cf. https://github.com/CanonicalLtd/ubuntu-core-docs/pull/8

> I am still worried that it sets a bad precedent. I still think that each set of documentation markdown files should be self-contained, and the relationship between markdown repositories and built HTML files should be direct and simple. And this breaks that.

> However, we do need a pattern for drawing together related sets of documentation. This should ideally be codified higher up the chain, with core functionality in documentation-builder or in the docs.ubuntu.com application, rather than hacked together with tools like git-repo in individual documentation sets. But unfortunately it doesn't look like creating and implementing the ideal solution can happen in time for this.

**Comment by nottrobin** [comment]
This issue is quite old, and the landscape of documentation is changing significantly as a result of https://github.com/canonical-websites/docs.ubuntu.com/issues/86.

I think the current system has been working fine, so for the time being I think we can close this, and just see if a similar issue pops up again in the new structure.
